% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{hyperref}
\hypersetup{
    colorlinks,
    linkcolor={blue!100!black},
    citecolor={blue!100!black},
    urlcolor={blue!100!black}
}
\usepackage{apacite}
\usepackage[round]{natbib} 
\usepackage{graphicx}
\usepackage{float}
\usepackage{caption}
\usepackage[toc,page]{appendix}
\usepackage{booktabs,caption}
\usepackage[flushleft]{threeparttable}
\usepackage{tabularx}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{xcolor}
\usepackage{scrextend}
\deffootnote[2em]{2em}{1em}{\textsuperscript{\thefootnotemark}\,}
\newcolumntype{Y}{>{\centering\arraybackslash}X}
%\usepackage[a4paper]{geometry}
\usepackage{caption}
\usepackage[bottom,flushmargin,hang,multiple]{footmisc}
\usepackage{pdflscape}
\usepackage[paper=portrait,pagesize]{typearea}
\usepackage{rotating}
\usepackage{fullpage}
\usepackage{tabu}
\usepackage{fontspec}
\usepackage{multirow}
\usepackage{multicol}
\usepackage{colortbl}
\usepackage{hhline}
\usepackage{longtable}
\usepackage{float}
\usepackage{wrapfig}
\usepackage{array}
\usepackage{hyperref}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[round]{natbib}
\bibliographystyle{sarb.bst}
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}


\title{Basel III and the supply of bank credit in South Africa}


\author { 
Alister Milner\footnote{Loughborough University,School of Business and Economics,United Kingdom; Email: A.K.L.Milne@lboro.ac.uk}  \,\, 
Xolani Sibande\footnote{South African Reserve Bank, South Africa; Email: xolani.sibande@resbank.co.za}
}
\date{\today}
\maketitle

\begin{abstract}


\end{abstract}

\noindent\textbf{Keywords}: Bank capital, Bank regulation, Credit   \\
\textbf{JEL Codes}: G01, G18, G28, G32, G38
\newpage

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

The paper investigates the impact of Basel III regulation on bank lending in South Africa. This introduction is an overview of the paper

\hypertarget{context}{%
\section{Context}\label{context}}

A review of policy context, with focus on South Africa but also reference to other emerging markets. Further detail in Appendix 1 and 2a.

\hypertarget{literature}{%
\section{Literature}\label{literature}}

\citet{osborne2017good}

\citet{jokipii2008cyclical}

\citet{gambacorta2004does}

\citet{schwert2018bank}

\citet{kim2017effect}

\citet{carlson2013capital}

\citet{tabak2011bank}

\citet{altunbas2004bank}

\citet{gambacorta2018bank}

\citet{berrospide2010effects}

\newpage

\hypertarget{developments-in-south-african-banking}{%
\section{Developments in South African Banking}\label{developments-in-south-african-banking}}

\begin{figure}[H]

\includegraphics{Bank_capital_and_bank_lending_files/figure-latex/unnamed-chunk-1-1} \hfill{}

\caption{Internatinal Comparison. Source: World Bank (2022)}\label{fig:unnamed-chunk-1}
\end{figure}

\begin{figure}[H]

\includegraphics{Bank_capital_and_bank_lending_files/figure-latex/unnamed-chunk-2-1} \hfill{}

\caption{Credit Cycle. Source: South African Reserve Bank (2022)}\label{fig:unnamed-chunk-2}
\end{figure}

\begin{figure}[H]

\includegraphics{Bank_capital_and_bank_lending_files/figure-latex/unnamed-chunk-3-1} \hfill{}

\caption{Capital Buffers. Source: South African Reserve Bank (2022)}\label{fig:unnamed-chunk-3}
\end{figure}

\begin{figure}[H]

\includegraphics{Bank_capital_and_bank_lending_files/figure-latex/unnamed-chunk-6-1} \hfill{}

\caption{Bank assets. Source: South African Reserve Bank (2022)}\label{fig:unnamed-chunk-6}
\end{figure}

\begin{figure}[H]

\includegraphics{Bank_capital_and_bank_lending_files/figure-latex/unnamed-chunk-7-1} \hfill{}

\caption{Lending Rates. Source: South African Reserve Bank (2022)}\label{fig:unnamed-chunk-7}
\end{figure}

\newpage

\hypertarget{specification}{%
\section{Specification}\label{specification}}

\hypertarget{estimation-results}{%
\section{Estimation Results}\label{estimation-results}}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{0pt}

\renewcommand*{\arraystretch}{0.6}

\begin{longtable}[l]{|p{1.32in}|p{2.36in}|p{0.61in}|p{0.53in}|p{0.61in}|p{0.46in}}



\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\ }}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\ }}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Median}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{SD}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Min}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Obs}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Lending\ Rates\ (\%)}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Corporate\ mortage\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{8.3}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{6.7}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{34}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Corporate\ secured\ credit\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.9}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.8}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{34}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Corporate\ unsecured\ credit\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{2.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.2}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1.6}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{34}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ mortage\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{9.2}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1.2}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{7.3}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{34}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ secured\ credit\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1.3}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{34}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ unsecured\ credit\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1.5}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.2}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{34}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Regulatory\ Capital\ (\%)}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Minimum\ requirement}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{10.7}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1.4}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{9.5}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{50}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Surplus\ capital}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{3.9}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.9}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{2.3}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{50}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Total\ Assets\ (R\ Billions)}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector\ secured\ credit}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{236.3}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{51.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{146.5}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{50}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector\ unsecured\ credit}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{327.7}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{92.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{148.9}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{50}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Households\ residential\ mortgages}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{781.3}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{93.9}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{630.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{50}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non-financial\ corporate\ sector\ mortgages}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{334.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{73.6}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{238.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{50}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non-financial\ corporate\ secured\ credit}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{98.9}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{20.7}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{76.5}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{50}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non-financial\ corporate\ unsecured\ credit}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{530.5}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{164.7}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{340.4}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{50}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other\ assets}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1,550.3}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{327.8}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1,200.6}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{50}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Total\ Assets/GDP\ (\%)}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector\ secured\ credit\ /\ GDP}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{5.4}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.3}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{5.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{44}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector\ unsecured\ credit\ /\ GDP}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{7.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.9}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{5.6}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{44}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Households\ residential\ mortgages\ /\ GDP}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{20.2}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{2.9}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{16.7}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{44}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non-financial\ corporate\ sector\ mortgages\ /\ GDP}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{8.8}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.9}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{8.3}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{44}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non-financial\ corporate\ secured\ credit\ /\ GDP}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{2.5}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{0.4}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{2.3}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{44}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non-financial\ corporate\ unsecured\ credit\ /\ GDP}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{13.5}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{1.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{11.2}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{44}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.32in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.36in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other\ assets\ /\ GDP}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{39.1}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.53in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{3.5}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.61in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{36.4}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.46in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{44}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\caption{Descriptives}\label{tab:unnamed-chunk-8}\\

\end{longtable}

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

\newpage

\hypertarget{appendix}{%
\section{Appendix}\label{appendix}}

\hypertarget{data-sources}{%
\subsection{Data Sources}\label{data-sources}}

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{0pt}

\renewcommand*{\arraystretch}{0.6}

\begin{longtable}[l]{|p{1.06in}|p{2.48in}|p{0.64in}|p{1.39in}|p{0.69in}}



\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.06in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\ }}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.48in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Description}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.64in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Frequency}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.39in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Availability}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.69in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Source}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.06in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{BA900}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.48in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Banking\ sector\ balance\ sheet\ data\ at\ a\ bank\ level}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.64in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Monthly}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.39in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Public\ data}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.69in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{SARB}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.06in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{BA930}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.48in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Banking\ sector\ lending\ rates\ at\ a\ bank\ level}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.64in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Monthly}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.39in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Aggregated\ data\ is\ public.\ }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Bank\ specific\ data\ is\ private}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.69in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{SARB}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.06in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Controls}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.48in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Banking\ sector\ performance\ data\ at\ a\ bank\ level}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.64in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Monthly}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.39in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Aggregated\ data\ is\ public.\ }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Bank\ specific\ data\ is\ private}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.69in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{PA}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.06in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{GDP}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.48in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Nominal\ and\ real\ gross\ domestic\ product}}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{in\ a\ calendar\ year}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.64in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Quarterly}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.39in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Public\ data}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.69in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{PA}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.06in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Capital\ buffer}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.48in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Basel\ III\ regulatory\ capital\ buffer\ requirement}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.64in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Monthly}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.39in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Aggregated\ data\ is\ public.\ }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Bank\ specific\ data\ is\ private}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.69in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Statssa}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.06in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Credit\ cycle}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.48in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Composite\ index\ of\ lending\ conditions\ in\ South\ Africa}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.64in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Monthly}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.39in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Public\ data}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.69in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{SARB}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.06in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Country\ comparison}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.48in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{International\ data\ on:}}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{domestic\ credit\ to\ private\ sector\ (\%\ of\ GDP),\ }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{bank\ return\ on\ assets\ (\%,\ before\ tax),\ }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{bank\ capital\ to\ total\ assets\ (\%),\ }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{and\ bank\ concentration\ (\%)}}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ }}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.64in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Yearly}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.39in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Public\ data}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.69in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{World\ Bank}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\caption{Data\ Description}\label{tab:data}\\

\end{longtable}

\newpage

\hypertarget{aggregation-schema}{%
\subsection{Aggregation schema}\label{aggregation-schema}}

The following tabulation is derived from the BA900s is the balance sheet return loan data (lines 103 to 277) and gives relative magnitudes by financial corporate sector, non-financial corporate sector and household sector. This is the most granular data provided. The missing item numbers are all aggregations of these numbers.

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{0pt}

\renewcommand*{\arraystretch}{0.6}

\begin{longtable}[l]{|p{1.60in}|p{0.70in}|p{2.94in}|p{0.85in}}



\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{BA\ 900\ Categories}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Item\ Number}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Aggregation\ Key}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Installment\ sales}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{141}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Financial\ corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{142}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non\ financial\ corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{a}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{143}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{c}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{144}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{a}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Leasing\ transactions}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{146}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Financial\ corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{147}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non\ financial\ corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{a}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{148}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{c}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{149}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{a}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Farm\ Mortgages}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{152}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non\ financial\ corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{153}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{154}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Residential\ Mortgages}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{156}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non\ financial\ corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{157}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{d}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{158}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Commercial\ and\ Other\ mortgages}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{160}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Public\ financial\ corporates}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{161}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Public\ non-financial\ corporates}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{162}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Private\ financial\ corporate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{163}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Private\ non-financial\ corporates}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{164}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{165}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Credit\ cards}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{167}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Financial\ corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{168}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non\ financial\ corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{a}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{169}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{c}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{170}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{c}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Overdrafts}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-7}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Public\ sector\ (includes\ public\ corporations\ and\ local\ government)}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{181}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Financial\ corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{182}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non\ financial\ corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{a}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{183}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Unincorporated\ business\ enterprises}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{e}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{184}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other\ Household\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{c}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{185}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Non-profit\ organisations\ serving\ households}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{c}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.6in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Factoring}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.7in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{187}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.94in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 0.85in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{a}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\caption{Aggregation\ schema}\label{tab:scheme}\\

\end{longtable}

The following aggregation scheme which results in six categories was followed based on Table \ref{tab:scheme}, with unincorporated enterprise credit as part of household unsecured lending.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Non-financial corporate sector secured credit: Items 142 + 147
\item
  Non-financial corporate sector unsecured credit: Items 168 + 182 + 187+ 190
\item
  Non-financial corporate sector mortgages (commercial and other mortgage advances): Items 152 + 153 + 154 + 156 + 158 + 163 + 164 + 165
\item
  Household sector secured credit: Items 143 + 148\\
\item
  Household sector unsecured credit: Items 169 + 184 + 185 + 192 + 193 + 183 + 191 (note includes unincorporated business enterprise credit last two items)
\item
  Household sector residential mortgages: Item 157
\end{enumerate}

\newpage

The loans quantities from the BA900s are then linked to the lending rate data from the BA930s using table to create six lending rate categories the schema on Table \ref{tab:schemelend}.

\providecommand{\docline}[3]{\noalign{\global\setlength{\arrayrulewidth}{#1}}\arrayrulecolor[HTML]{#2}\cline{#3}}

\setlength{\tabcolsep}{0pt}

\renewcommand*{\arraystretch}{0.6}

\begin{longtable}[l]{|p{1.44in}|p{2.40in}|p{1.25in}|p{1.31in}}



\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{BA\ 930\ Categories}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Item\ Number}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Weighting\ Key}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}\endhead



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Corporate\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Overdrafts}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{48.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Instalment\ sale\ agreements\ flexible\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{49.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{a}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Instalment\ sale\ fixed\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{50.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Leasing\ transactions\ flexible\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{51.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{a}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Leasing\ transactions\ fixed\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{52.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Mortgage\ advances\ flexible\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{53.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{c}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Mortgage\ advances\ fixed\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{54.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Credit\ cards}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{55.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{56.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{b}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Household\ sector}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Overdrafts}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{58.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{e}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Instalment\ sale\ agreements\ flexible\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{59.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{d}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Instalment\ sale\ fixed\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{60.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Leasing\ transactions\ flexible\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{61.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{d}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Leasing\ transactions\ fixed\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{62.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Mortgage\ advances\ flexible\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{63.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{f}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Mortgage\ advances\ fixed\ rate}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{64.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{-}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Credit\ cards}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{65.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{e}}}} \\

\hhline{>{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}->{\arrayrulecolor[HTML]{FFFFFF}\global\arrayrulewidth=1pt}-}



\multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.44in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 2.4in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{Other}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.25in+0\tabcolsep+0\arrayrulewidth}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{66.0}}}} & \multicolumn{1}{!{\color[HTML]{FFFFFF}\vrule width 1pt}>{\raggedright}p{\dimexpr 1.31in+0\tabcolsep+0\arrayrulewidth}!{\color[HTML]{FFFFFF}\vrule width 1pt}}{\textcolor[HTML]{000000}{\fontsize{7}{7}\selectfont{\global\setmainfont{Helvetica}{e}}}} \\

\hhline{>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}-}

\caption{Weighting\ schema}\label{tab:schemelend}\\

\end{longtable}

The six categories, therefore, are as follows:

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Non-financial corporate sector secured credit rate: Weighted average of items 49 + 51
\item
  Non-financial corporate sector unsecured credit rate: Weighted average items 48 + 55 + 56
\item
  Non-financial corporate sector mortgage rate: Item 53
\item
  Household sector secured credit rate: Weighted average of items 59 + 61
\item
  Household sector unsecured credit rate: Weighted average of items 58 + 65 + 66
\item
  Household sector residential mortgages: Item 63
\end{enumerate}

\newpage

\hypertarget{appendix-descriptive-analysis}{%
\section{Appendix: Descriptive Analysis}\label{appendix-descriptive-analysis}}

\newpage

\newpage

\hypertarget{appendix-detailed-literature-review}{%
\section{Appendix: Detailed Literature Review}\label{appendix-detailed-literature-review}}

More detailed literature review

\newpage

\renewcommand\refname{References}
  \bibliography{references.bib}

\end{document}
