---
output:
  bookdown::word_document2:
    fig_width: 5 
    fig_height: 4
    reference_docx: new_template_no_numbering.docx
    
  bookdown::pdf_document2:
    citation_package: natbib
    fig_caption: yes
    latex_engine: xelatex
    number_sections: yes
    toc: no
    keep_tex: true
    includes:
      in_header: preamble.tex
      before_body: title.tex
      after_body: appendix_backcover.tex
# title: "A Pandoc Markdown Article Starter and Template"
# thanks: "Replication files are available on the author's Github account..."
# author:
# date: "`r format(Sys.time(), '%B %d, %Y')`"
# abstract:
#  "This document provides an introduction to R Markdown, argues for its...  \\par \\textbf{Keywords:} one, two, three " 
# fontfamily: mathpazo
# fontsize: 12
# spacing: double
# documentclass: article
# classoption: fleqn
# paper: a4
csl: ucl-institute-of-education-harvard.csl
bibliography: references.bib
biblio-style: sarb.bst
natbiboptions: round
# link-citations: no
# linkcolor: blue!000!black
# urlcolor: blue!000!black
# citecolor: blue!000!black
# linestretch: 1.5
# indent: TRUE
---

```{r setup, include=FALSE}
options(scipen=999)
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      dpi = 500, 
                      fig.pos = "H", 
                      fig.align = "left", 
                      fig.env= 'figure', 
                      out.height = '50%', 
                      tab.topcaption = FALSE,
                      ft.align = "left")
options(xtable.floating = TRUE,
        xtable.caption.placement = 'top', # notice \floatsetup overrides
        xtable.include.rownames = FALSE,
        xtable.comment = FALSE,
        xtable.booktabs = TRUE,
        xtable.table.placement = "H",
        xtable.tabular.environment = "tabularx",
        xtable.NA.string = "NA", 
        xtable.width = "\\textwidth", 
        xtable.size = "\\tiny", 
        xtable.hline.after = c(-1,0)
        )

```

```{r loading_packages, echo=FALSE}
library(tidyverse)
library(readr)
library(readxl)
library(zoo)
library(magick)
library(stringi)
library(patchwork)
library(xtable)
library(scales)
library(rvest)
library(rebus)
library(PNWColors)
library(lubridate)
library(here)
library(flextable)
library(gt)
library(officer)
library(modelsummary)

theme <-
  theme_minimal(base_size = 6) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none",) # EU base theme
theme_set(theme) # setting ggplot theme instead of using theme function
```

```{r, functions}

```

# Bank capital and lending in South Africa {.unnumbered}

# Introduction


# Literature

@osborne2017good

@jokipii2008cyclical

@gambacorta2004does

@schwert2018bank

@kim2017effect

@carlson2013capital

@tabak2011bank

@altunbas2004bank

@gambacorta2018bank

@berrospide2010effects

# Methodology

# Results

# Conclusion

\newpage
# References
